version: '3.3'
services:
  backend:
    build: .
    ports:
      - 8080:8080
    healthcheck:
      test: curl http://localhost:8080/ || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
